### ISSUE TITLE
Could you provide the OKVQA ans2label

### ISSUE THREAD

**Issue by PamelaDDD** [guoyang9/UnifER#1]
Hi sir. Could you provide the content in the OKVQA cache folder?  I can't run this code because I don't know how to build the ans2label.json and label2ans.json

**Comment by guoyang9** [comment]
Please spend a few minutes read the `ReadMe` file first.
After run `python tools/answer_parse_okvqa.py`, you will find these json files.

**Comment by PamelaDDD** [comment]
Thank you for your answer. How much memory is needed to train the model?

**Comment by guoyang9** [comment]
I forget the details. 
For the largest model (ViLT), with the pre-defined `batch size`, the GPU memory is definitely less than 20G, maybe 16G.

**Comment by PamelaDDD** [comment]
Thanks！ I run the program sucessfully. However, how do I get the final accuracy? Do I need to run vqaEvalDemo.py in the vqa_eval directory?

**Comment by guoyang9** [comment]
Good!
For the accuracy, no need, just wait for the printed log.
