### ISSUE TITLE
Could you please tell me how to download the complete dataset

### ISSUE THREAD

**Issue by ZYMblog** [guoyang9/UnifER#2]
Excuse me. Your job is really great. I want to have a further study. But I got trouble in the first step. Could you please tell me how to download the complete dataset? or where I can find the download way. Because I couldn't find the resources on https://paperswithcode.com/paper/190600067.

**Comment by guoyang9** [comment]
See the dataset website below
https://okvqa.allenai.org/download.html.

**Comment by ZYMblog** [comment]
> See the dataset website below https://okvqa.allenai.org/download.html.
Oh, really thank you! I'm going to do it now~
Happy mid-Autumn Festival :)

**Comment by ZYMblog** [comment]
ModuleNotFoundError: No module named 'param'   
In your project, 'param.py' is under the root directory, and args = parse_args(). When I run 'python answer_parse_okvqa.py' in '/tool/answer_parse.py', the shell window show that 'ModuleNotFoundError: No module named 'param''. How could I solve it ?

**Comment by guoyang9** [comment]
`python tools/answer_parse_okvqa.py 
`

**Comment by ZYMblog** [comment]
Thanks! I have solved it. And it is excuting the 'Extract knowledge base with Roberta'. I want to know if I only have cpu to train it , is it also ok? I mean change the codes from '.cuda()' to '.cpu()'.
