### ISSUE TITLE
 Why is the loss a two-dimensional vector？

### ISSUE THREAD

**Issue by zhongfansun** [guoyang9/UnifER#3]
Thank you very much for providing the code. But the following error occurred when I ran the program
![image](https://user-images.githubusercontent.com/102452634/192769238-cc00abf3-fba1-4948-ab10-79af65980aab.png)
It is found that the loss is a two-dimensional vector. Have you encountered this problem before？

**Comment by guoyang9** [comment]
Did you modify the original codes other than the data paths?

**Comment by zhongfansun** [comment]
> 

I didn't modify the original codes other than the data paths. I check it and downloaded your code again. But the same problem occurs. I print the two losses
![image](https://user-images.githubusercontent.com/102452634/192774164-cc0de153-028c-4192-9276-701226632296.png)
It can be seen that these two losses are two-dimensional vectors.

**Comment by zhongfansun** [comment]
The only difference is that I used two GPUs, and run _python main.py --name unifer --gpu 1,2
_. I think that's not the reason for this error.

**Comment by zhongfansun** [comment]
Sorry, I know why. Since loss is calculated in multiple GPUs, multiple losses are returned.

**Comment by guoyang9** [comment]
Nevermind.
I forgot to test data-parallel over multiple gpus. 
Feel free to contribute if you implement this!
