### ISSUE TITLE
how to process fvqa dataset

### ISSUE THREAD

**Issue by PamelaDDD** [guoyang9/UnifER#4]
Hello, Scholar. Can you provide the imagefeatures in fvqa, which can be used for  lxmert/ visualbert model

**Comment by guoyang9** [comment]
Try this google drive link: 
https://drive.google.com/file/d/1jms24nRTiEdiv9naKm70tY1QMsR3ZiFk/view?usp=sharing.

**Comment by PamelaDDD** [comment]
thanks for your help


Pamela
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guoyang9/UnifER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月22日(星期二) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guoyang9/UnifER] how to process fvqa dataset (Issue #4)





 
Try this google drive link:
 https://drive.google.com/file/d/1jms24nRTiEdiv9naKm70tY1QMsR3ZiFk/view?usp=sharing.
