### ISSUE TITLE
About the training environment

### ISSUE THREAD

**Issue by Gary-code** [guoyang9/UnifER#6]
I choose ViLT as the backbone. I am curious about what kind of gpu you use and the batch size setup, since I get the cuda out of memory issue with 3 RTX 2080 Ti

**Comment by guoyang9** [comment]
Hi, I tested on a single A5000 GPU with 24G yet not using full memory. 
If the 11G 2080Ti cannot work with the current batch size, maybe you can try a smaller one.

**Comment by Gary-code** [comment]
Thanks for your reply. I think the batch size setting is not the major reason for the issue and I change the bs to 2. 
I debug and find that [line91](https://github.com/guoyang9/UnifER/blob/3b543f8c57214aaadbc45573bb56e95086c24152/modules/model_build.py#L91) cost much cuda memory, since the number of knowledge in OKVQA is 1199797.

**Comment by CZP686** [comment]
> 感谢您的回复。我认为批量大小设置不是问题的主要原因，我将 bs 更改为 2。我调试并发现 [line91](https://github.com/guoyang9/UnifER/blob/3b543f8c57214aaadbc45573bb56e95086c24152/modules/model_build.py#L91) 花费了很多 cuda 内存，因为 OKVQA 中的知识数量1199797。

Hello, have you solved your problem at last?

**Comment by Gary-code** [comment]
> > 感谢您的回复。我认为批量大小设置不是问题的主要原因，我将 bs 更改为 2。我调试并发现 [line91](https://github.com/guoyang9/UnifER/blob/3b543f8c57214aaadbc45573bb56e95086c24152/modules/model_build.py#L91) 花费了很多 cuda 内存，因为 OKVQA 中的知识数量1199797。
> 
> Hello, have you solved your problem at last?

yep, just split the knowledge embedding into 2 gpus to calculate
